### ISSUE TITLE
There is a bug in the UI of signup

### ISSUE THREAD

**Issue by izam-mohammed** [Auto-Playground/thalia#55]
**Describe the bug**
The UI of the signup page is broken in my system

**Screenshots**
![Screenshot from 2024-03-10 00-05-51](https://github.com/Auto-Playground/thalia/assets/106471909/b7103ce7-7d3b-4d7c-ba67-9f65fc89835c)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Browser chrome

**Additional context**
nothing

**Comment by SHUHAIB-T** [comment]
solved the issue in the recent PR (#64 )
